name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - run: docker login ghcr.io -u ${{ github.actor }} -p ${{ github.token }}
      - uses: actions/checkout@v3
      - run: docker build --platform linux/amd64 --tag ghcr.io/hfhbd/cobol2java:${{ github.sha }} .
      - run: docker run -v $(pwd):/output ghcr.io/hfhbd/cobol2java:${{ github.sha }} cobc HELLO.cbl
      - run: docker push ghcr.io/hfhbd/cobol2java:${{ github.sha }}
